PUB-1995 Add testing support endpoints
hmcts/pip-subscription-management pull request #236
Opened 2023-06-26 14:10 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1995

### Change description ###

Add testing support endpoints

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-06-27 15:12 UTC, ChrisS1512 requested changes

2023-06-27 15:12 UTC, ChrisS1512 commented on charts/pip-subscription-management/values.stg.template.yaml
> +  environment:
Same comment as other PR's regarding SDS flux

2023-06-28 13:49 UTC, ChrisS1512 approved these changes

2023-06-29 12:37 UTC, NatashaAlker approved these changes

2023-07-05 10:45 UTC, merged