PUB-2079 Update dependencies
hmcts/pip-subscription-management pull request #252
Opened 2023-07-05 11:27 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2079

### Change description ###

 Update dependencies

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-06 10:21 UTC, ChrisS1512 requested changes

2023-07-06 10:21 UTC, ChrisS1512 commented on README.md
> -| ENABLE_TESTING_SUPPORT_API     | Used to conditionally enable testing support API. Default to `false` for the production environment only.
I think this should be added back in

2023-07-06 14:04 UTC, KianKwa commented on README.md
> -| ENABLE_TESTING_SUPPORT_API     | Used to conditionally enable testing support API. Default to `false` for the production environment only.
Have now added

2023-07-06 14:21 UTC, ChrisS1512 approved these changes

2023-07-07 08:37 UTC, joshblackmoor approved these changes

2023-07-07 13:42 UTC, merged