PUB-1511 Location subscription by ListType
hmcts/pip-subscription-management pull request #76
Opened 2022-08-17 14:13 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1511

### Change description ###

A verified user can subscriber to specific list type for a particular court. 

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-08-18 13:03 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
> +    @Query(value = "SELECT * FROM Subscription "
I have made the changes. I add extra where clause on SearchType to make sure that only relevant search is being called by the code.

2022-08-18 15:27 UTC, KianKwa approved these changes

2022-08-19 11:21 UTC, ChrisS1512 requested changes

2022-08-19 11:21 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
> +        + "AND (ARRAY_LENGTH(list_type, 1) IS NULL OR (list_type && string_to_array(:list_type, ',')))",
Just to check would that also return if the array is empty as well as null? Or does it need to be a null array

2022-08-19 11:45 UTC, ChrisS1512 approved these changes

2022-09-06 11:14 UTC, joshblackmoor commented
Was merged in other PR.

2022-09-06 11:14 UTC, closed without merging